name: louvores_app
description: A new Flutter application
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0" # Ajuste a versão conforme necessário

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  json_annotation: ^4.4.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.5

flutter:
  assets:
    - assets/louvores.json